version: '3.7'
services:
   server:
      build:
         context: ./server
         dockerfile: Dockerfile
      image: hh-server
      ports:
         - 127.0.0.1:5000:5000
      deploy:
         mode: replicated
         replicas: 1
         restart_policy:
            condition: on-failure

   app:
      build:
         context: ./app
         dockerfile: Dockerfile
      image: hh-client
      ports:
         - 127.0.0.1:3000:3000
      deploy:
         mode: replicated
         replicas: 1
         restart_policy:
            condition: on-failure
